# Generated by Django 3.2 on 2022-07-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('take_off', models.DateTimeField()),
                ('landing', models.DateTimeField()),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_airport', to='api.airport', verbose_name='from')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_airport', to='api.airport', verbose_name='to')),
            ],
        ),
    ]
